# Keep a list of physical devices
# <DEVICE_NAME>:<DEVICE ID>
# Give your devices a meaningful name. A name that could easily tell the device type and os
# The device name will be passed to a rake task(s) for execution.
# You can get your device id by plugging your device via USB and running the command 'adb devices' on your terminal.
# Your device may need to be setup for development.

# For example:
googlenexus5: 192.168.56.101:5555
# droid_maxx_kitkat_444: TA96106AQK

motog: ZX1D63R8X7

nexus6: ZX1G426T8X

nexus6s: ENU7N15C15002990